name: Dev-Test

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ master ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  # 1️⃣ CodeQL analysis (manual build)
  codeql_analysis:
    name: CodeQL Analysis (Java + Kotlin)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['java-kotlin']
        build-mode: ['manual']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix['build-mode'] }}
          queries: security-extended
          dependency-caching: true

      - name: Build project
        run: |
          chmod +x ./gradlew
          ./gradlew clean assemble

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

  # 2️⃣ Run tests when CodeQL passed
  run_tests:
    name: Run Kotlin/Java Tests
    needs: codeql_analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant Gradle wrapper exec permission
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test

  # 3️⃣ Manual review reminder only on PRs, after tests succeed
  manual_review_notice:
    name: Manual Code Review Notification
    needs: run_tests
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Post PR comment for manual review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: [
                '🔍 **Manual Code Review Required**',
                '',
                `@${pr.user.login} your changes have passed CodeQL and all tests.`,
                'Please review the code, inspect any findings, and approve or request changes before merging.'
              ].join('\n')
            });
