name: Manual Code Review Reminder

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

jobs:
  manual_review_notice:
    name: Manual Code Review Notification
    runs-on: ubuntu-latest
    steps:
      - name: Post PR Comment for Manual Review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.createComment({
              issue_number: pr.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🔍 **Manual Code Review Required**  A new or updated pull request has been submitted by @${pr.user.login}.📋 Please review the code and leave feedback or approve the PR before it can be merged.`
            });
