on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]
  schedule:
    - cron: '0 2 * * 0'  # optional weekly scan

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql_analysis:
    name: CodeQL Analysis (Java + Kotlin)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java-kotlin' ]
        build-mode: [ 'autobuild' ]
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          queries: security-extended
          dependency-caching: true
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3

  manual_review_notice:
    name: Manual Review Notification
    runs-on: ubuntu-latest
    needs: codeql_analysis
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `🔍 **Manual Code Review Required**\n\n@${pr.user.login} opened or updated this PR. ✅ CodeQL results are in — please review code & security alerts before merging.`
            })
