name: Kotlin CodeQL + Manual Review Reminder

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  codeql_analysis:
    name: CodeQL Analysis (Java + Kotlin)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ['java-kotlin']
        build-mode: ['manual']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          queries: security-extended
          dependency-caching: true

      - name: Build Kotlin/Java project
        run: |
          ./gradlew clean assemble
          
      - name: Analyze with CodeQL
        uses: github/codeql-action/analyze@v3

  manual_review_notice:
    name: Manual Review Notification
    needs: codeql_analysis
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Post PR comment for manual review
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `🔍 **Manual Code Review Required**\n\nA pull request by @${pr.user.login} was updated—CodeQL has completed. Please review code, inspect the results, and approve before merging.`
            });
