name: Tag on merge to main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate tag
        id: tag
        uses: amitsingh-007/next-release-tag@v6.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          tag_template: 'yyyy.WW.E.i'

      - name: Create and push tag
        run: |
          git tag ${{ steps.tag.outputs.next_release_tag }}
          git push origin ${{ steps.tag.outputs.next_release_tag }}
